FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
# Эта переменная — магия, которая заставляет инструменты сборки AppImage
# работать внутри Docker без FUSE
ENV APPIMAGE_EXTRACT_AND_RUN=1

RUN apt-get update && apt-get install -y \
    curl \
    wget \
    build-essential \
    libssl-dev \
    libgtk-3-dev \
    libwebkit2gtk-4.1-dev \
    libayatana-appindicator3-dev \
    librsvg2-dev \
    javascriptcoregtk-4.1 \
    xdg-utils \
    # Добавляем эти три пакета:
    libfuse2 \
    file \
    binutils \
    && rm -rf /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs

WORKDIR /app

CMD npm install && npm run tauri build; \
    EXIT_CODE=$?; \
    echo "Fixing permissions..."; \
    chown -R $(stat -c '%u:%g' /app) /app/src-tauri/target /app/node_modules; \
    exit $EXIT_CODE
    